spring:

  datasource:
    password: Alimnikas299
    username: root
    url: jdbc:mysql://localhost:3306/weather_db

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    validate-on-migrate: true
    user: root
    password: Alimnikas299
    baseline-version: 0
    baseline-description: "init"

logging:
  level:
    sql: info
    web: info